name: CI

on:
  pull_request:
    # Temporarily run on any PR changes to test CI
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    # Temporarily run on pushes to any branch to test CI
    branches: ['**']

jobs:
  format-and-lint-check:
    name: Ruff format and lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Ruff format check (src)
        run: ruff format --check src

      - name: Ruff lint (src)
        run: ruff check src

  package-and-upload:
    name: Package Lambda and upload artifacts to S3
    needs: format-and-lint-check
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ARTIFACT_BUCKET_NAME: ${{ vars.ARTIFACT_BUCKET_NAME || secrets.ARTIFACT_BUCKET_NAME }}
      WRITER_ROLE_ARN: ${{ vars.WRITER_ROLE_ARN || secrets.WRITER_ROLE_ARN }}
      AWS_REGION: ${{ vars.AWS_REGION || secrets.AWS_REGION }}
      ARTIFACT_PREFIX: concurrency-eval-python
    steps:
      - name: Validate required configuration
        shell: bash
        run: |
          set -euo pipefail
          : "${ARTIFACT_BUCKET_NAME?Define ARTIFACT_BUCKET_NAME as a Repository/Environment variable or Secret}"
          : "${WRITER_ROLE_ARN?Define WRITER_ROLE_ARN as a Repository/Environment variable or Secret}"
          : "${AWS_REGION?Define AWS_REGION as a Repository/Environment variable or Secret}"
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Export dependencies to requirements.txt from uv.lock
        run: uv export --frozen --no-dev -o requirements.txt

      - name: Prepare Lambda layer (Python dependencies)
        run: |
          set -euxo pipefail
          mkdir -p build/layer/python
          # If requirements.txt exists, install deps into layer; otherwise create an empty layer structure
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt -t build/layer/python
          else
            echo "No requirements.txt found; building an empty layer (stdlib-only)."
          fi
          (cd build/layer && zip -r ../layer.zip .)

      - name: Package Lambda function code
        run: |
          set -euxo pipefail
          mkdir -p build/function
          cp src/lambda_function.py build/function/
          (cd build/function && zip -r ../function.zip .)

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.WRITER_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-artifact-upload

      - name: Upload artifacts to S3
        env:
          BUCKET: ${{ env.ARTIFACT_BUCKET_NAME }}
          PREFIX: ${{ env.ARTIFACT_PREFIX }}
        run: |
          set -euxo pipefail
          LAYER_KEY="${PREFIX}/lambda_layer.zip"
          FUNC_KEY="${PREFIX}/lambda_function.zip"
          aws s3 cp build/layer.zip "s3://${BUCKET}/${LAYER_KEY}"
          aws s3 cp build/function.zip "s3://${BUCKET}/${FUNC_KEY}"
          echo "layer_s3_uri=s3://${BUCKET}/${LAYER_KEY}" >> "$GITHUB_OUTPUT"
          echo "function_s3_uri=s3://${BUCKET}/${FUNC_KEY}" >> "$GITHUB_OUTPUT"

      - name: Summary
        env:
          PREFIX: ${{ env.ARTIFACT_PREFIX }}
        run: |
          echo "Artifacts uploaded (latest via S3 object versions):" >> $GITHUB_STEP_SUMMARY
          echo "- Layer: s3://${{ env.ARTIFACT_BUCKET_NAME }}/${PREFIX}/lambda_layer.zip" >> $GITHUB_STEP_SUMMARY
          echo "- Function: s3://${{ env.ARTIFACT_BUCKET_NAME }}/${PREFIX}/lambda_function.zip" >> $GITHUB_STEP_SUMMARY
