name: PR Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  format-and-lint-check:
    name: Ruff format and lint check
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Ruff format check (src)
        run: ruff format --check src

      - name: Ruff lint (src)
        run: ruff check src

      - name: Install lizard
        run: pip install --disable-pip-version-check --no-input lizard

      - name: Run lizard on main Lambda file only
        run: |
          # Check only the main file and fail on warnings
          # -C: cyclomatic complexity threshold (warn if function > 10)
          # -L: maximum function length (lines) threshold (warn if function > 120)
          # --fail-on-warnings: non-zero exit if any warnings are found
          lizard -l python -C 10 -L 120 --fail-on-warnings src/lambda_function.py
